name: Deploy BirdWatch

on:
  push:
    branches: [ "main" ]

jobs:

  deploy-pi:
    runs-on: self-hosted
    steps:
      - name: Update Pi recorder
        run: |
          cd /home/pi/BirdingWatch
          git pull
          sudo systemctl restart birdwatch-recorder


  deploy-cloud:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy cloud server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.CLOUD_HOST }}
          username: ${{ secrets.CLOUD_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd /root/BirdingWatch/server
            git pull
            sudo systemctl restart birdwatch